# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 550

[directory]
# number of parent folders to show
truncation_length = 5
truncate_to_repo = true

[cmd_duration]
min_time = 200 # ms

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count ⇣$behind_count"
modified = ""

[memory_usage]
# includes file-system cache so is nearly always full
disabled = true

[time]
disabled = false
time_format = "%_H:%M"
format = "[$time]($style) "
style = "yellow"

[username]
disabled = true

[hostname]
format="[@$hostname]($style) "
style = "bold green"

[aws]
disabled = true

## language-specific configuration

[nodejs]
disabled = true

[golang]
symbol = "Go "

[package]
# used for npm, cargo, and poetry (Python)
symbol = "pkg "

[rust]
symbol = ""

[python]
disabled = true

[perl]
disabled = true

[ocaml]
detect_extensions = ["ml", "mli"]
detect_files = [".merlin", ".ocamlformat", ".ocamlinit"]
