(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(LaTeX-fold-math-spec-list
   '(("→"
      ("to"))
     ("←"
      ("gets"))
     ("α"
      ("alpha"))
     ("β"
      ("beta"))
     ("γ"
      ("gamma"))
     ("δ"
      ("delta"))
     ("ϵ"
      ("epsilon"))
     ("ζ"
      ("zeta"))
     ("η"
      ("eta"))
     ("θ"
      ("theta"))
     ("ι"
      ("iota"))
     ("κ"
      ("kappa"))
     ("λ"
      ("lambda"))
     ("μ"
      ("mu"))
     ("ν"
      ("nu"))
     ("ξ"
      ("xi"))
     ("π"
      ("pi"))
     ("ρ"
      ("rho"))
     ("σ"
      ("sigma"))
     ("τ"
      ("tau"))
     ("υ"
      ("upsilon"))
     ("ϕ"
      ("phi"))
     ("χ"
      ("chi"))
     ("ψ"
      ("psi"))
     ("ω"
      ("omega"))
     ("ε"
      ("varepsilon"))
     ("ϑ"
      ("vartheta"))
     ("ϖ"
      ("varpi"))
     ("ϱ"
      ("varrho"))
     ("ς"
      ("varsigma"))
     ("φ"
      ("varphi"))
     ("Γ"
      ("Gamma"))
     ("Δ"
      ("Delta"))
     ("Θ"
      ("Theta"))
     ("Λ"
      ("Lambda"))
     ("Ξ"
      ("Xi"))
     ("Π"
      ("Pi"))
     ("Σ"
      ("Sigma"))
     ("ϒ"
      ("Upsilon"))
     ("Φ"
      ("Phi"))
     ("Ψ"
      ("Psi"))
     ("Ω"
      ("Omega"))
     ("±"
      ("pm"))
     ("∓"
      ("mp"))
     ("×"
      ("times"))
     ("÷"
      ("div"))
     ("∗"
      ("ast"))
     ("⋆"
      ("star"))
     ("∘"
      ("circ"))
     ("∙"
      ("bullet"))
     ("⋅"
      ("cdot"))
     ("∩"
      ("cap"))
     ("∪"
      ("cup"))
     ("⊎"
      ("uplus"))
     ("⊓"
      ("sqcap"))
     ("∨"
      ("vee"))
     ("∧"
      ("wedge"))
     ("∖"
      ("setminus"))
     ("≀"
      ("wr"))
     ("⋄"
      ("diamond"))
     ("△"
      ("bigtriangleup"))
     ("▽"
      ("bigtriangledown"))
     ("◁"
      ("triangleleft"))
     ("▷"
      ("triangleright"))
     ("⊲"
      ("lhd"))
     ("⊳"
      ("rhd"))
     ("⊴"
      ("unlhd"))
     ("⊵"
      ("unrhd"))
     ("⊕"
      ("oplus"))
     ("⊖"
      ("ominus"))
     ("⊗"
      ("otimes"))
     ("∅"
      ("oslash"))
     ("⊙"
      ("odot"))
     ("○"
      ("bigcirc"))
     ("†"
      ("dagger"))
     ("‡"
      ("ddagger"))
     ("⨿"
      ("amalg"))
     ("≤"
      ("leq"))
     ("≥"
      ("geq"))
     ("∎"
      ("qed"))
     ("≡"
      ("equiv"))
     ("⊧"
      ("models"))
     ("≺"
      ("prec"))
     ("≻"
      ("succ"))
     ("∼"
      ("sim"))
     ("⟂"
      ("perp"))
     ("⪯"
      ("preceq"))
     ("⪰"
      ("succeq"))
     ("≃"
      ("simeq"))
     ("∣"
      ("mid"))
     ("≪"
      ("ll"))
     ("≫"
      ("gg"))
     ("≍"
      ("asymp"))
     ("∥"
      ("parallel"))
     ("⊂"
      ("subset"))
     ("⊃"
      ("supset"))
     ("≈"
      ("approx"))
     ("⋈"
      ("bowtie"))
     ("⊆"
      ("subseteq"))
     ("⊇"
      ("supseteq"))
     ("≅"
      ("cong"))
     ("⨝"
      ("Join"))
     ("⊏"
      ("sqsubset"))
     ("⊐"
      ("sqsupset"))
     ("≠"
      ("neq"))
     ("⌣"
      ("smile"))
     ("⊑"
      ("sqsubseteq"))
     ("⊒"
      ("sqsupseteq"))
     ("≐"
      ("doteq"))
     ("⌢"
      ("frown"))
     ("∈"
      ("in"))
     ("∋"
      ("ni"))
     ("∝"
      ("propto"))
     ("⊢"
      ("vdash"))
     ("⊣"
      ("dashv"))
     ("←"
      ("leftarrow"))
     ("⇐"
      ("Leftarrow"))
     ("→"
      ("rightarrow"))
     ("⇒"
      ("Rightarrow"))
     ("↔"
      ("leftrightarrow"))
     ("⇔"
      ("Leftrightarrow"))
     ("↦"
      ("mapsto"))
     ("↩"
      ("hookleftarrow"))
     ("↼"
      ("leftharpoonup"))
     ("↽"
      ("leftharpoondown"))
     ("⟵"
      ("longleftarrow"))
     ("⟸"
      ("Longleftarrow"))
     ("⟶"
      ("longrightarrow"))
     ("⟹"
      ("Longrightarrow"))
     ("⟷"
      ("longleftrightarrow"))
     ("⟺"
      ("Longleftrightarrow"))
     ("⟺"
      ("iff"))
     ("⟼"
      ("longmapsto"))
     ("↪"
      ("hookrightarrow"))
     ("⇀"
      ("rightharpoonup"))
     ("⇁"
      ("rightharpoondown"))
     ("↑"
      ("uparrow"))
     ("⇑"
      ("Uparrow"))
     ("↓"
      ("downarrow"))
     ("⇓"
      ("Downarrow"))
     ("↕"
      ("updownarrow"))
     ("⇕"
      ("Updownarrow"))
     ("↗"
      ("nearrow"))
     ("↘"
      ("searrow"))
     ("↙"
      ("swarrow"))
     ("↖"
      ("nwarrow"))
     ("…"
      ("ldots"))
     ("⋯"
      ("cdots"))
     ("⋮"
      ("vdots"))
     ("⋱"
      ("ddots"))
     (":"
      ("colon"))
     ("∇"
      ("nabla"))
     ("ℵ"
      ("aleph"))
     ("′"
      ("prime"))
     ("∀"
      ("forall"))
     ("∞"
      ("infty"))
     ("ℏ"
      ("hbar"))
     ("∅"
      ("emptyset"))
     ("∃"
      ("exists"))
     ("√"
      ("surd"))
     ("□"
      ("Box"))
     ("△"
      ("triangle"))
     ("◇"
      ("Diamond"))
     ("𝚤"
      ("imath"))
     ("𝚥"
      ("jmath"))
     ("ℓ"
      ("ell"))
     ("¬"
      ("neg"))
     ("̸"
      ("not"))
     ("⊤"
      ("top"))
     ("♭"
      ("flat"))
     ("♮"
      ("natural"))
     ("♯"
      ("sharp"))
     ("℘"
      ("wp"))
     ("⊥"
      ("bot"))
     ("♣"
      ("clubsuit"))
     ("♢"
      ("diamondsuit"))
     ("♡"
      ("heartsuit"))
     ("♠"
      ("spadesuit"))
     ("℧"
      ("mho"))
     ("ℜ"
      ("Re"))
     ("ℑ"
      ("Im"))
     ("∠"
      ("angle"))
     ("∂"
      ("partial"))
     ("∑"
      ("sum"))
     ("∏"
      ("prod"))
     ("∐"
      ("coprod"))
     ("∫"
      ("int"))
     ("∮"
      ("oint"))
     ("⋂"
      ("bigcap"))
     ("⋃"
      ("bigcup"))
     ("⨆"
      ("bigsqcup"))
     ("⋁"
      ("bigvee"))
     ("⋀"
      ("bigwedge"))
     ("⨀"
      ("bigodot"))
     ("⨂"
      ("bigotimes"))
     ("⨁"
      ("bigoplus"))
     ("⨄"
      ("biguplus"))
     ("{"
      ("{"))
     ("}"
      ("}"))
     ("⌊"
      ("lfloor"))
     ("⌋"
      ("rfloor"))
     ("⌈"
      ("lceil"))
     ("⌉"
      ("rceil"))
     ("⟨"
      ("langle"))
     ("⟩"
      ("rangle"))
     ("⎱"
      ("rmoustache"))
     ("⎰"
      ("lmoustache"))
     ("⎭"
      ("rgroup"))
     ("⎩"
      ("lgroup"))
     ("\\"
      ("backslash"))
     ("‖"
      ("|"))
     ("ℶ"
      ("beth"))
     ("ℸ"
      ("daleth"))
     ("ℷ"
      ("gimel"))
     ("ϝ"
      ("digamma"))
     ("ϰ"
      ("varkappa"))
     ("𝛤"
      ("varGamma"))
     ("𝛥"
      ("varDelta"))
     ("𝛩"
      ("varTheta"))
     ("𝛬"
      ("varLambda"))
     ("𝛯"
      ("varXi"))
     ("𝛱"
      ("varPi"))
     ("𝛴"
      ("varSigma"))
     ("𝛶"
      ("varUpsilon"))
     ("𝛷"
      ("varPhi"))
     ("𝛹"
      ("varPsi"))
     ("𝛺"
      ("varOmega"))
     ("⟸"
      ("impliedby"))
     ("⟹"
      ("implies"))
     ("⇇"
      ("leftleftarrows"))
     ("⇆"
      ("leftrightarrows"))
     ("⇚"
      ("Lleftarrow"))
     ("↞"
      ("twoheadleftarrow"))
     ("↢"
      ("leftarrowtail"))
     ("↫"
      ("looparrowleft"))
     ("⇋"
      ("leftrightharpoons"))
     ("↶"
      ("curvearrowleft"))
     ("↺"
      ("circlearrowleft"))
     ("↰"
      ("Lsh"))
     ("⇈"
      ("upuparrows"))
     ("↿"
      ("upharpoonleft"))
     ("⇃"
      ("downharpoonleft"))
     ("⊸"
      ("multimap"))
     ("↭"
      ("leftrightsquigarrow"))
     ("↬"
      ("looparrowright"))
     ("⇌"
      ("rightleftharpoons"))
     ("↷"
      ("curvearrowright"))
     ("↱"
      ("Rsh"))
     ("⇊"
      ("downdownarrows"))
     ("↾"
      ("upharpoonright"))
     ("⇂"
      ("downharpoonright"))
     ("↝"
      ("rightsquigarrow"))
     ("↚"
      ("nleftarrow"))
     ("↛"
      ("nrightarrow"))
     ("⇍"
      ("nLeftarrow"))
     ("⇏"
      ("nRightarrow"))
     ("↮"
      ("nleftrightarrow"))
     ("⇎"
      ("nLeftrightarrow"))
     ("≦"
      ("leqq"))
     ("⩽"
      ("leqslant"))
     ("⪕"
      ("eqslantless"))
     ("≲"
      ("lesssim"))
     ("⪅"
      ("lessapprox"))
     ("≊"
      ("approxeq"))
     ("⋖"
      ("lessdot"))
     ("⋘"
      ("lll"))
     ("≶"
      ("lessgtr"))
     ("⋚"
      ("lesseqgtr"))
     ("⪋"
      ("lesseqqgtr"))
     ("≑"
      ("doteqdot"))
     ("≓"
      ("risingdotseq"))
     ("≒"
      ("fallingdotseq"))
     ("∽"
      ("backsim"))
     ("⋍"
      ("backsimeq"))
     ("⫅"
      ("subseteqq"))
     ("⋐"
      ("Subset"))
     ("⊏"
      ("sqsubset"))
     ("≼"
      ("preccurlyeq"))
     ("⋞"
      ("curlyeqprec"))
     ("≾"
      ("precsim"))
     ("⪷"
      ("precapprox"))
     ("⊲"
      ("vartriangleleft"))
     ("⊴"
      ("trianglelefteq"))
     ("⊨"
      ("vDash"))
     ("⊪"
      ("Vvdash"))
     ("⌣"
      ("smallsmile"))
     ("⌢"
      ("smallfrown"))
     ("≏"
      ("bumpeq"))
     ("≎"
      ("Bumpeq"))
     ("≧"
      ("geqq"))
     ("⩾"
      ("geqslant"))
     ("⪖"
      ("eqslantgtr"))
     ("≳"
      ("gtrsim"))
     ("⪆"
      ("gtrapprox"))
     ("⋗"
      ("gtrdot"))
     ("⋙"
      ("ggg"))
     ("≷"
      ("gtrless"))
     ("⋛"
      ("gtreqless"))
     ("⪌"
      ("gtreqqless"))
     ("≖"
      ("eqcirc"))
     ("≗"
      ("circeq"))
     ("≜"
      ("triangleq"))
     ("∼"
      ("thicksim"))
     ("≈"
      ("thickapprox"))
     ("⫆"
      ("supseteqq"))
     ("⋑"
      ("Supset"))
     ("⊐"
      ("sqsupset"))
     ("≽"
      ("succcurlyeq"))
     ("⋟"
      ("curlyeqsucc"))
     ("≿"
      ("succsim"))
     ("⪸"
      ("succapprox"))
     ("⊳"
      ("vartriangleright"))
     ("⊵"
      ("trianglerighteq"))
     ("⊩"
      ("Vdash"))
     ("∣"
      ("shortmid"))
     ("∥"
      ("shortparallel"))
     ("≬"
      ("between"))
     ("⋔"
      ("pitchfork"))
     ("∝"
      ("varpropto"))
     ("◀"
      ("blacktriangleleft"))
     ("∴"
      ("therefore"))
     ("϶"
      ("backepsilon"))
     ("▶"
      ("blacktriangleright"))
     ("∵"
      ("because"))
     ("≮"
      ("nless"))
     ("≰"
      ("nleq"))
     ("⪇"
      ("lneq"))
     ("≨"
      ("lneqq"))
     ("⋦"
      ("lnsim"))
     ("⪉"
      ("lnapprox"))
     ("⊀"
      ("nprec"))
     ("⋨"
      ("precnsim"))
     ("⪹"
      ("precnapprox"))
     ("≁"
      ("nsim"))
     ("∤"
      ("nshortmid"))
     ("∤"
      ("nmid"))
     ("⊬"
      ("nvdash"))
     ("⊭"
      ("nvDash"))
     ("⋪"
      ("ntriangleleft"))
     ("⋬"
      ("ntrianglelefteq"))
     ("⊈"
      ("nsubseteq"))
     ("⊊"
      ("subsetneq"))
     ("⫋"
      ("subsetneqq"))
     ("≯"
      ("ngtr"))
     ("≱"
      ("ngeq"))
     ("⪈"
      ("gneq"))
     ("≩"
      ("gneqq"))
     ("⋧"
      ("gnsim"))
     ("⪊"
      ("gnapprox"))
     ("⊁"
      ("nsucc"))
     ("⋩"
      ("succnsim"))
     ("⪺"
      ("succnapprox"))
     ("≇"
      ("ncong"))
     ("∦"
      ("nshortparallel"))
     ("∦"
      ("nparallel"))
     ("⊭"
      ("nvDash"))
     ("⊯"
      ("nVDash"))
     ("⋫"
      ("ntriangleright"))
     ("⋭"
      ("ntrianglerighteq"))
     ("⊉"
      ("nsupseteq"))
     ("⊋"
      ("supsetneq"))
     ("⫌"
      ("supsetneqq"))
     ("∔"
      ("dotplus"))
     ("∖"
      ("smallsetminus"))
     ("⋒"
      ("Cap"))
     ("⋓"
      ("Cup"))
     ("⊼"
      ("barwedge"))
     ("⊻"
      ("veebar"))
     ("⌆"
      ("doublebarwedge"))
     ("⊟"
      ("boxminus"))
     ("⊠"
      ("boxtimes"))
     ("⊡"
      ("boxdot"))
     ("⊞"
      ("boxplus"))
     ("⋇"
      ("divideontimes"))
     ("⋉"
      ("ltimes"))
     ("⋊"
      ("rtimes"))
     ("⋋"
      ("leftthreetimes"))
     ("⋌"
      ("rightthreetimes"))
     ("⋏"
      ("curlywedge"))
     ("⋎"
      ("curlyvee"))
     ("⊝"
      ("circleddash"))
     ("⊛"
      ("circledast"))
     ("⊚"
      ("circledcirc"))
     ("⊺"
      ("intercal"))
     ("ℏ"
      ("hbar"))
     ("ℏ"
      ("hslash"))
     ("▵"
      ("vartriangle"))
     ("▿"
      ("triangledown"))
     ("□"
      ("square"))
     ("◊"
      ("lozenge"))
     ("Ⓢ"
      ("circledS"))
     ("∠"
      ("angle"))
     ("∡"
      ("measuredangle"))
     ("∄"
      ("nexists"))
     ("℧"
      ("mho"))
     ("Ⅎ"
      ("Finv"))
     ("⅁"
      ("Game"))
     ("𝕜"
      ("Bbbk"))
     ("‵"
      ("backprime"))
     ("∅"
      ("varnothing"))
     ("▴"
      ("blacktriangle"))
     ("▾"
      ("blacktriangledown"))
     ("■"
      ("blacksquare"))
     ("⧫"
      ("blacklozenge"))
     ("★"
      ("bigstar"))
     ("∢"
      ("sphericalangle"))
     ("∁"
      ("complement"))
     ("ð"
      ("eth"))
     ("╱"
      ("diagup"))
     ("╲"
      ("diagdown"))
     ("⌜"
      ("ulcorner"))
     ("⌝"
      ("urcorner"))
     ("⌞"
      ("llcorner"))
     ("⌟"
      ("lrcorner"))
     ("∗"
      ("sep"))
     ("==∗"
      ("vs"))))
 '(LaTeX-verbatim-macros-with-braces '("cc"))
 '(company-coq-disabled-features '(hello prettify-symbols alerts spinner company-defaults))
 '(custom-safe-themes
   '("2f1518e906a8b60fac943d02ad415f1d8b3933a5a7f75e307e6e9a26ef5bf570" "e1ecb0536abec692b5a5e845067d75273fe36f24d01210bf0aa5842f2a7e029f" "99ea831ca79a916f1bd789de366b639d09811501e8c092c85b2cb7d697777f93" "6cbf6003e137485fb3f904e76fb15bc48abc386540f43f54e2a47a9884e679f6" default))
 '(dafny-prover-args '("/compile:0"))
 '(preview-auto-cache-preamble t)
 '(safe-local-variable-values
   '((dafny-prover-local-args "/noNLarith" "/arith:5")
     (dafny-prover-local-args "/z3opt:smt.arith.nl=true" "/arith:1")
     (dafny-prover-local-args "/z3opt:smt.arith.nl=false" "/arith:5")
     (dafny-prover-local-args "/z3opt:smt.arith.nl=true")
     (dafny-prover-local-args "/z3opt:smt.arith.nl=false")
     (reftex-default-bibliography "n.bib" "paper.bib")
     (reftex-default-bibliography "n.bib" "p.bib")))
 '(vterm-shell "/usr/local/bin/fish"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(variable-pitch ((t (:family "Helvetica Neue
")))))
