(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(LaTeX-fold-math-spec-list
   '(("→" ("to")) ("←" ("gets")) ("α" ("alpha")) ("β" ("beta")) ("γ" ("gamma"))
     ("δ" ("delta")) ("ϵ" ("epsilon")) ("ζ" ("zeta")) ("η" ("eta"))
     ("θ" ("theta")) ("ι" ("iota")) ("κ" ("kappa")) ("λ" ("lambda"))
     ("μ" ("mu")) ("ν" ("nu")) ("ξ" ("xi")) ("π" ("pi")) ("ρ" ("rho"))
     ("σ" ("sigma")) ("τ" ("tau")) ("υ" ("upsilon")) ("ϕ" ("phi")) ("χ" ("chi"))
     ("ψ" ("psi")) ("ω" ("omega")) ("ε" ("varepsilon")) ("ϑ" ("vartheta"))
     ("ϖ" ("varpi")) ("ϱ" ("varrho")) ("ς" ("varsigma")) ("φ" ("varphi"))
     ("Γ" ("Gamma")) ("Δ" ("Delta")) ("Θ" ("Theta")) ("Λ" ("Lambda"))
     ("Ξ" ("Xi")) ("Π" ("Pi")) ("Σ" ("Sigma")) ("ϒ" ("Upsilon")) ("Φ" ("Phi"))
     ("Ψ" ("Psi")) ("Ω" ("Omega")) ("±" ("pm")) ("∓" ("mp")) ("×" ("times"))
     ("÷" ("div")) ("∗" ("ast")) ("⋆" ("star")) ("∘" ("circ")) ("∙" ("bullet"))
     ("⋅" ("cdot")) ("∩" ("cap")) ("∪" ("cup")) ("⊎" ("uplus")) ("⊓" ("sqcap"))
     ("∨" ("vee")) ("∧" ("wedge")) ("∖" ("setminus")) ("≀" ("wr"))
     ("⋄" ("diamond")) ("△" ("bigtriangleup")) ("▽" ("bigtriangledown"))
     ("◁" ("triangleleft")) ("▷" ("triangleright")) ("⊲" ("lhd")) ("⊳" ("rhd"))
     ("⊴" ("unlhd")) ("⊵" ("unrhd")) ("⊕" ("oplus")) ("⊖" ("ominus"))
     ("⊗" ("otimes")) ("∅" ("oslash")) ("⊙" ("odot")) ("○" ("bigcirc"))
     ("†" ("dagger")) ("‡" ("ddagger")) ("⨿" ("amalg")) ("≤" ("leq"))
     ("≥" ("geq")) ("∎" ("qed")) ("≡" ("equiv")) ("⊧" ("models")) ("≺" ("prec"))
     ("≻" ("succ")) ("∼" ("sim")) ("⟂" ("perp")) ("⪯" ("preceq"))
     ("⪰" ("succeq")) ("≃" ("simeq")) ("∣" ("mid")) ("≪" ("ll")) ("≫" ("gg"))
     ("≍" ("asymp")) ("∥" ("parallel")) ("⊂" ("subset")) ("⊃" ("supset"))
     ("≈" ("approx")) ("⋈" ("bowtie")) ("⊆" ("subseteq")) ("⊇" ("supseteq"))
     ("≅" ("cong")) ("⨝" ("Join")) ("⊏" ("sqsubset")) ("⊐" ("sqsupset"))
     ("≠" ("neq")) ("⌣" ("smile")) ("⊑" ("sqsubseteq")) ("⊒" ("sqsupseteq"))
     ("≐" ("doteq")) ("⌢" ("frown")) ("∈" ("in")) ("∋" ("ni")) ("∝" ("propto"))
     ("⊢" ("vdash")) ("⊣" ("dashv")) ("←" ("leftarrow")) ("⇐" ("Leftarrow"))
     ("→" ("rightarrow")) ("⇒" ("Rightarrow")) ("↔" ("leftrightarrow"))
     ("⇔" ("Leftrightarrow")) ("↦" ("mapsto")) ("↩" ("hookleftarrow"))
     ("↼" ("leftharpoonup")) ("↽" ("leftharpoondown")) ("⟵" ("longleftarrow"))
     ("⟸" ("Longleftarrow")) ("⟶" ("longrightarrow")) ("⟹" ("Longrightarrow"))
     ("⟷" ("longleftrightarrow")) ("⟺" ("Longleftrightarrow")) ("⟺" ("iff"))
     ("⟼" ("longmapsto")) ("↪" ("hookrightarrow")) ("⇀" ("rightharpoonup"))
     ("⇁" ("rightharpoondown")) ("↑" ("uparrow")) ("⇑" ("Uparrow"))
     ("↓" ("downarrow")) ("⇓" ("Downarrow")) ("↕" ("updownarrow"))
     ("⇕" ("Updownarrow")) ("↗" ("nearrow")) ("↘" ("searrow")) ("↙" ("swarrow"))
     ("↖" ("nwarrow")) ("…" ("ldots")) ("⋯" ("cdots")) ("⋮" ("vdots"))
     ("⋱" ("ddots")) (":" ("colon")) ("∇" ("nabla")) ("ℵ" ("aleph"))
     ("′" ("prime")) ("∀" ("forall")) ("∞" ("infty")) ("ℏ" ("hbar"))
     ("∅" ("emptyset")) ("∃" ("exists")) ("√" ("surd")) ("□" ("Box"))
     ("△" ("triangle")) ("◇" ("Diamond")) ("𝚤" ("imath")) ("𝚥" ("jmath"))
     ("ℓ" ("ell")) ("¬" ("neg")) ("̸" ("not")) ("⊤" ("top")) ("♭" ("flat"))
     ("♮" ("natural")) ("♯" ("sharp")) ("℘" ("wp")) ("⊥" ("bot"))
     ("♣" ("clubsuit")) ("♢" ("diamondsuit")) ("♡" ("heartsuit"))
     ("♠" ("spadesuit")) ("℧" ("mho")) ("ℜ" ("Re")) ("ℑ" ("Im")) ("∠" ("angle"))
     ("∂" ("partial")) ("∑" ("sum")) ("∏" ("prod")) ("∐" ("coprod"))
     ("∫" ("int")) ("∮" ("oint")) ("⋂" ("bigcap")) ("⋃" ("bigcup"))
     ("⨆" ("bigsqcup")) ("⋁" ("bigvee")) ("⋀" ("bigwedge")) ("⨀" ("bigodot"))
     ("⨂" ("bigotimes")) ("⨁" ("bigoplus")) ("⨄" ("biguplus")) ("{" ("{"))
     ("}" ("}")) ("⌊" ("lfloor")) ("⌋" ("rfloor")) ("⌈" ("lceil"))
     ("⌉" ("rceil")) ("⟨" ("langle")) ("⟩" ("rangle")) ("⎱" ("rmoustache"))
     ("⎰" ("lmoustache")) ("⎭" ("rgroup")) ("⎩" ("lgroup")) ("\\" ("backslash"))
     ("‖" ("|")) ("ℶ" ("beth")) ("ℸ" ("daleth")) ("ℷ" ("gimel"))
     ("ϝ" ("digamma")) ("ϰ" ("varkappa")) ("𝛤" ("varGamma")) ("𝛥" ("varDelta"))
     ("𝛩" ("varTheta")) ("𝛬" ("varLambda")) ("𝛯" ("varXi")) ("𝛱" ("varPi"))
     ("𝛴" ("varSigma")) ("𝛶" ("varUpsilon")) ("𝛷" ("varPhi")) ("𝛹" ("varPsi"))
     ("𝛺" ("varOmega")) ("⟸" ("impliedby")) ("⟹" ("implies"))
     ("⇇" ("leftleftarrows")) ("⇆" ("leftrightarrows")) ("⇚" ("Lleftarrow"))
     ("↞" ("twoheadleftarrow")) ("↢" ("leftarrowtail")) ("↫" ("looparrowleft"))
     ("⇋" ("leftrightharpoons")) ("↶" ("curvearrowleft"))
     ("↺" ("circlearrowleft")) ("↰" ("Lsh")) ("⇈" ("upuparrows"))
     ("↿" ("upharpoonleft")) ("⇃" ("downharpoonleft")) ("⊸" ("multimap"))
     ("↭" ("leftrightsquigarrow")) ("↬" ("looparrowright"))
     ("⇌" ("rightleftharpoons")) ("↷" ("curvearrowright")) ("↱" ("Rsh"))
     ("⇊" ("downdownarrows")) ("↾" ("upharpoonright"))
     ("⇂" ("downharpoonright")) ("↝" ("rightsquigarrow")) ("↚" ("nleftarrow"))
     ("↛" ("nrightarrow")) ("⇍" ("nLeftarrow")) ("⇏" ("nRightarrow"))
     ("↮" ("nleftrightarrow")) ("⇎" ("nLeftrightarrow")) ("≦" ("leqq"))
     ("⩽" ("leqslant")) ("⪕" ("eqslantless")) ("≲" ("lesssim"))
     ("⪅" ("lessapprox")) ("≊" ("approxeq")) ("⋖" ("lessdot")) ("⋘" ("lll"))
     ("≶" ("lessgtr")) ("⋚" ("lesseqgtr")) ("⪋" ("lesseqqgtr"))
     ("≑" ("doteqdot")) ("≓" ("risingdotseq")) ("≒" ("fallingdotseq"))
     ("∽" ("backsim")) ("⋍" ("backsimeq")) ("⫅" ("subseteqq")) ("⋐" ("Subset"))
     ("⊏" ("sqsubset")) ("≼" ("preccurlyeq")) ("⋞" ("curlyeqprec"))
     ("≾" ("precsim")) ("⪷" ("precapprox")) ("⊲" ("vartriangleleft"))
     ("⊴" ("trianglelefteq")) ("⊨" ("vDash")) ("⊪" ("Vvdash"))
     ("⌣" ("smallsmile")) ("⌢" ("smallfrown")) ("≏" ("bumpeq")) ("≎" ("Bumpeq"))
     ("≧" ("geqq")) ("⩾" ("geqslant")) ("⪖" ("eqslantgtr")) ("≳" ("gtrsim"))
     ("⪆" ("gtrapprox")) ("⋗" ("gtrdot")) ("⋙" ("ggg")) ("≷" ("gtrless"))
     ("⋛" ("gtreqless")) ("⪌" ("gtreqqless")) ("≖" ("eqcirc")) ("≗" ("circeq"))
     ("≜" ("triangleq")) ("∼" ("thicksim")) ("≈" ("thickapprox"))
     ("⫆" ("supseteqq")) ("⋑" ("Supset")) ("⊐" ("sqsupset"))
     ("≽" ("succcurlyeq")) ("⋟" ("curlyeqsucc")) ("≿" ("succsim"))
     ("⪸" ("succapprox")) ("⊳" ("vartriangleright")) ("⊵" ("trianglerighteq"))
     ("⊩" ("Vdash")) ("∣" ("shortmid")) ("∥" ("shortparallel"))
     ("≬" ("between")) ("⋔" ("pitchfork")) ("∝" ("varpropto"))
     ("◀" ("blacktriangleleft")) ("∴" ("therefore")) ("϶" ("backepsilon"))
     ("▶" ("blacktriangleright")) ("∵" ("because")) ("≮" ("nless"))
     ("≰" ("nleq")) ("⪇" ("lneq")) ("≨" ("lneqq")) ("⋦" ("lnsim"))
     ("⪉" ("lnapprox")) ("⊀" ("nprec")) ("⋨" ("precnsim")) ("⪹" ("precnapprox"))
     ("≁" ("nsim")) ("∤" ("nshortmid")) ("∤" ("nmid")) ("⊬" ("nvdash"))
     ("⊭" ("nvDash")) ("⋪" ("ntriangleleft")) ("⋬" ("ntrianglelefteq"))
     ("⊈" ("nsubseteq")) ("⊊" ("subsetneq")) ("⫋" ("subsetneqq")) ("≯" ("ngtr"))
     ("≱" ("ngeq")) ("⪈" ("gneq")) ("≩" ("gneqq")) ("⋧" ("gnsim"))
     ("⪊" ("gnapprox")) ("⊁" ("nsucc")) ("⋩" ("succnsim")) ("⪺" ("succnapprox"))
     ("≇" ("ncong")) ("∦" ("nshortparallel")) ("∦" ("nparallel"))
     ("⊭" ("nvDash")) ("⊯" ("nVDash")) ("⋫" ("ntriangleright"))
     ("⋭" ("ntrianglerighteq")) ("⊉" ("nsupseteq")) ("⊋" ("supsetneq"))
     ("⫌" ("supsetneqq")) ("∔" ("dotplus")) ("∖" ("smallsetminus"))
     ("⋒" ("Cap")) ("⋓" ("Cup")) ("⊼" ("barwedge")) ("⊻" ("veebar"))
     ("⌆" ("doublebarwedge")) ("⊟" ("boxminus")) ("⊠" ("boxtimes"))
     ("⊡" ("boxdot")) ("⊞" ("boxplus")) ("⋇" ("divideontimes")) ("⋉" ("ltimes"))
     ("⋊" ("rtimes")) ("⋋" ("leftthreetimes")) ("⋌" ("rightthreetimes"))
     ("⋏" ("curlywedge")) ("⋎" ("curlyvee")) ("⊝" ("circleddash"))
     ("⊛" ("circledast")) ("⊚" ("circledcirc")) ("⊺" ("intercal"))
     ("ℏ" ("hbar")) ("ℏ" ("hslash")) ("▵" ("vartriangle"))
     ("▿" ("triangledown")) ("□" ("square")) ("◊" ("lozenge"))
     ("Ⓢ" ("circledS")) ("∠" ("angle")) ("∡" ("measuredangle"))
     ("∄" ("nexists")) ("℧" ("mho")) ("Ⅎ" ("Finv")) ("⅁" ("Game"))
     ("𝕜" ("Bbbk")) ("‵" ("backprime")) ("∅" ("varnothing"))
     ("▴" ("blacktriangle")) ("▾" ("blacktriangledown")) ("■" ("blacksquare"))
     ("⧫" ("blacklozenge")) ("★" ("bigstar")) ("∢" ("sphericalangle"))
     ("∁" ("complement")) ("ð" ("eth")) ("╱" ("diagup")) ("╲" ("diagdown"))
     ("⌜" ("ulcorner")) ("⌝" ("urcorner")) ("⌞" ("llcorner")) ("⌟" ("lrcorner"))
     ("∗" ("sep")) ("==∗" ("vs"))))
 '(LaTeX-verbatim-macros-with-braces '("cc"))
 '(ansi-color-names-vector
   ["#fafafa" "#e45649" "#50a14f" "#986801" "#4078f2" "#a626a4" "#0184bc" "#383a42"])
 '(coq-prog-name "coqtop")
 '(custom-safe-themes
   '("0325a6b5eea7e5febae709dab35ec8648908af12cf2d2b569bedc8da0a3a81c1"
     "5c7720c63b729140ed88cf35413f36c728ab7c70f8cd8422d9ee1cedeb618de5"
     "88f7ee5594021c60a4a6a1c275614103de8c1435d6d08cc58882f920e0cec65e"
     "9f297216c88ca3f47e5f10f8bd884ab24ac5bc9d884f0f23589b0a46a608fe14"
     "02f57ef0a20b7f61adce51445b68b2a7e832648ce2e7efb19d217b6454c1b644"
     "afa47084cb0beb684281f480aa84dab7c9170b084423c7f87ba755b15f6776ef"
     "835868dcd17131ba8b9619d14c67c127aa18b90a82438c8613586331129dda63"
     "246a9596178bb806c5f41e5b571546bb6e0f4bd41a9da0df5dfbca7ec6e2250c"
     "6c386d159853b0ee6695b45e64f598ed45bd67c47f671f69100817d7db64724d"
     "88f59acbeacefb4998f45126d4d8ae8b2184f2a48753db362a349fd55321c7e1"
     "63bfcabeb44559c67d8827dc68cd6c4a6d3ce35ef4504343af12d42f24894e00"
     "cebda623e3f9ecd4a4af08d92c406bc4517e323d9259d5156f43901860224e30"
     "8f5a7a9a3c510ef9cbb88e600c0b4c53cdcdb502cfe3eb50040b7e13c6f4e78e"
     "f4876796ef5ee9c82b125a096a590c9891cec31320569fc6ff602ff99ed73dca"
     "2f1518e906a8b60fac943d02ad415f1d8b3933a5a7f75e307e6e9a26ef5bf570"
     "e1ecb0536abec692b5a5e845067d75273fe36f24d01210bf0aa5842f2a7e029f"
     "99ea831ca79a916f1bd789de366b639d09811501e8c092c85b2cb7d697777f93"
     "6cbf6003e137485fb3f904e76fb15bc48abc386540f43f54e2a47a9884e679f6" default))
 '(dafny-prover-args '("/compile:0"))
 '(exwm-floating-border-color "#c8c8c8")
 '(fci-rule-color "#383a42")
 '(highlight-tail-colors
   ((("#e9f1e8" "#50a14f" "green") . 0) (("#e1eef3" "#0184bc" "brightcyan") . 20)))
 '(jdee-db-active-breakpoint-face-colors (cons "#f0f0f0" "#4078f2"))
 '(jdee-db-requested-breakpoint-face-colors (cons "#f0f0f0" "#50a14f"))
 '(jdee-db-spec-breakpoint-face-colors (cons "#f0f0f0" "#9ca0a4"))
 '(lsp-dafny-preferred-version 'path)
 '(magit-todos-insert-after '(bottom) nil nil "Changed by setter of obsolete option `magit-todos-insert-at'")
 '(objed-cursor-color "#e45649")
 '(pdf-view-midnight-colors (cons "#383a42" "#fafafa"))
 '(preview-auto-cache-preamble t)
 '(proof-shell-strip-crs-from-input t)
 '(rustic-ansi-faces
   ["#fafafa" "#e45649" "#50a14f" "#986801" "#4078f2" "#a626a4" "#0184bc" "#383a42"])
 '(safe-local-variable-values
   '((reftex-default-bibliography "paper-zotero.bib" "paper.bib")
     (reftex-default-bibliography "paper.bib" "paper-zotero.bib")
     (reftex-default-bibliography . "proposal.bib")
     (reftex-default-bibliography quote ("proposal.bib")) (auto-fill-mode . -1)
     (fill-column)
     (whitespace-style (tabs) (line-end-newline . t) (newline . t)
      (space-before-tab) (tab-width . 8))
     (tex-main-file . "thesis.tex")
     (git-commit-major-mode . git-commit-elisp-text-mode)
     (dafny-prover-local-args "/noNLarith" "/arith:5")
     (dafny-prover-local-args "/z3opt:smt.arith.nl=true" "/arith:1")
     (dafny-prover-local-args "/z3opt:smt.arith.nl=false" "/arith:5")
     (dafny-prover-local-args "/z3opt:smt.arith.nl=true")
     (dafny-prover-local-args "/z3opt:smt.arith.nl=false")
     (reftex-default-bibliography "n.bib" "paper.bib")
     (reftex-default-bibliography "n.bib" "p.bib")))
 '(sh-basic-offset 2)
 '(standard-indent 2)
 '(vc-annotate-background "#fafafa")
 '(vc-annotate-color-map
   (list (cons 20 "#50a14f") (cons 40 "#688e35") (cons 60 "#807b1b")
         (cons 80 "#986801") (cons 100 "#ae7118") (cons 120 "#c37b30")
         (cons 140 "#da8548") (cons 160 "#c86566") (cons 180 "#b74585")
         (cons 200 "#a626a4") (cons 220 "#ba3685") (cons 240 "#cf4667")
         (cons 260 "#e45649") (cons 280 "#d2685f") (cons 300 "#c07b76")
         (cons 320 "#ae8d8d") (cons 340 "#383a42") (cons 360 "#383a42")))
 '(vc-annotate-very-old-color nil)
 '(vterm-shell "fish")
 '(writeroom-width 60))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
